# This file was generated by GoReleaser. DO NOT EDIT.
class Scharf < Formula
  desc "Prevent supply-chain attacks from your third-party GitHub actions"
  homepage "https://github.com/cybrota/scharf"
  version "0.5.1"
  license "Apache-2.0"
  version_scheme 1

  on_macos do
    on_intel do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Darwin_x86_64.zip",
          using: CurlDownloadStrategy
      sha256 "7eaf6fd3837385d2a405069e452d3ef2e6543ab999ea52fe8e7d3af89b197f90"
  
      def install
        bin.install "scharf"
      end
    end

    on_arm do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Darwin_arm64.zip",
          using: CurlDownloadStrategy
      sha256 "8823c95fc130e44523c62e399a2c277bf4e8cb4d5dd26bb4d69a382dc2bf2933"
  
      def install
        bin.install "scharf"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Linux_x86_64.zip",
          using: CurlDownloadStrategy
      sha256 "0a59c564c5178ad1d7982e9f026300faaffaa606d5ef7c51e84a3ebf56e3d929"

      def install
        bin.install "scharf"
      end
    end

    on_arm do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Linux_arm64.zip",
          using: CurlDownloadStrategy
      sha256 "e7acee237780289af35aa6075cfea9bbf90b1b2a64ce67f3278d2bf02df933db"

      def install
        bin.install "scharf"
      end
    end
  end
end
