# This file was generated by GoReleaser. DO NOT EDIT.
class Scharf < Formula
  desc "Prevent supply-chain attacks from your third-party GitHub actions"
  homepage "https://github.com/cybrota/scharf"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Darwin_x86_64.zip",
          using: CurlDownloadStrategy
      sha256 "1e258b02fe6665300d8e6616a34fc67de5bf979166c53392d1afa4b1112fc229"
  
      def install
        bin.install "scharf"
      end
    end

    on_arm do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Darwin_arm64.zip",
          using: CurlDownloadStrategy
      sha256 "72c3258182a5956a9374512b92380e926acc0e5d1c5f4688b2c5ec06aa949fb6"
  
      def install
        bin.install "scharf"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Linux_x86_64.zip",
          using: CurlDownloadStrategy
      sha256 "cf1c384843d59ac76756b9bae745070fc671ceb15d15fc69e45ca68c15de541d"

      def install
        bin.install "scharf"
      end
    end

    on_arm do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Linux_arm64.zip",
          using: CurlDownloadStrategy
      sha256 "a202751b76bc2caedfa76f75803e05739473b495fab1934c78f59df31b45702d"

      def install
        bin.install "scharf"
      end
    end
  end
end
