# This file was generated by GoReleaser. DO NOT EDIT.
class Scharf < Formula
  desc "Prevent supply-chain attacks from your third-party GitHub actions"
  homepage "https://github.com/cybrota/scharf"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Darwin_x86_64.zip",
          using: CurlDownloadStrategy
      sha256 "d165943fd6b7050b291cf1926748a96ac3431e247098c4e7e174e7423f2dc43f"
  
      def install
        bin.install "scharf"
      end
    end

    on_arm do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Darwin_arm64.zip",
          using: CurlDownloadStrategy
      sha256 "7384d23cff6d0262390644a866fc084965ab7899bdaf29dec0f74fd6f5e91b07"
  
      def install
        bin.install "scharf"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Linux_x86_64.zip",
          using: CurlDownloadStrategy
      sha256 "ea8b9a52c973ee7357014b01cfc8da269f6b7a12899e70f6733b0e533eba6801"

      def install
        bin.install "scharf"
      end
    end

    on_arm do
      url "https://github.com/cybrota/scharf/releases/download/v#{version}/scharf_Linux_arm64.zip",
          using: CurlDownloadStrategy
      sha256 "840ae247b78c399ff4828dda01c9a28f061a30b008346e528baf23300e695249"

      def install
        bin.install "scharf"
      end
    end
  end
end
